### ISSUE TITLE
Change CE interface user/pass from default 

### ISSUE THREAD

**Issue by neurofog** [SkymindIO/SKIL-CE#1]
Is there a method for changing the default password for the SKIL CE interface?

**Comment by jpatanooga** [comment]
not currently, will update that in the point release in the next 30 days or so

**Comment by ShamsUlAzeem** [comment]
@neurofog There's going to be a v1.2.x on our [dockerhub](https://hub.docker.com/r/skymindops/skil-ce/). Stay tuned for it. It's going to let you set a password at startup

**Comment by ShamsUlAzeem** [comment]
This feature is implemented in the new release: https://skymind.ai/download
