### ISSUE TITLE
Toggle from Notebook to Models triggers red error flag

### ISSUE THREAD

**Issue by nkwoh01** [SkymindIO/SKIL-CE#11]
A red flag appears in the bottom right corner stating "Experiment / Syntax:Error Unexpected" untriggered. It came up a few times during the following

- Created an experiment
- ran test data
- It appears every time that I toggle from Notebook to Models
![screen shot 2018-01-08 at 4 44 21 pm](https://user-images.githubusercontent.com/35175038/34699861-91b8feee-f494-11e7-9417-21199796c28d.png)

**Comment by jpatanooga** [comment]
can you tell us which platform this was on? (OS, docker or RPM install)

**Comment by nkwoh01** [comment]
this is occurring on docker

**Comment by jpatanooga** [comment]
thanks ---

which operating system is docker running on?

**Comment by nkwoh01** [comment]
docker on macOS Sierra - not High Sierra

**Comment by wmeddie** [comment]
How much memory does your docker VM have?  When it runs out of memory many things tend to go wrong.

**Comment by nkwoh01** [comment]
How do I check how much memory the docker VM has?

On Sat, Jan 13, 2018 at 10:32 PM, Eduardo Gonzalez <notifications@github.com

**Comment by saudet** [comment]
Looks like by default it's only 2 GB:
> **Memory**
By default, Docker for Mac is set to use 2 GB runtime memory, allocated from the total available memory on your Mac. You can increase the RAM on the app to get faster performance by setting this number higher (for example to 3) or lower (to 1) if you want Docker for Mac to use less memory.

https://docs.docker.com/docker-for-mac/

**Comment by slinlee** [comment]
@nkwoh01 Did adding RAM to your docker help with this? If not, feel free to re-open this issue. 

At the very least, I've improved that cryptic error message via https://github.com/SkymindIO/lagom-skil-api/pull/1269
