### ISSUE TITLE
Receiving error message dialog when clicking Create Experimental Notebook button

### ISSUE THREAD

**Issue by JavaFXpert** [SkymindIO/SKIL-CE#13]
When choosing to create a New Experiment from a workspace, and filling out the Create Experiment dialog, I am consistently (every time) receiving a red message dialog that states "Create notebook / SyntaxError: Unexpected token < in JSON at position 2" after clicking the Create Experimental Notebook button. What can be done to get past this error?

Additional information: The first time I tried this operation it successfully created a notebook, but now I get that message. Also, the workspace that I originally created disappeared, so each time I log in it seems necessary to create a workspace and and experiment. I'm running SKIL CE using Docker on Windows.

**Comment by ejunprung** [comment]
@slinlee I'm having this issue as well. Attached is a screenshot of the issue. This is for skymindops/skil-ce:1.0.1-5.

![screen shot 2018-01-09 at 11 27 01 pm](https://user-images.githubusercontent.com/5703667/34760485-e1bec7ce-f594-11e7-9399-3774ce837520.png)

**Comment by slinlee** [comment]
I wasn't able to reproduce this myself, but working with @ejunprung we saw that the call to create the experiment returns the 500 error. The response is an HTML page with this message: 
`Oops, an error occurred
This exception has been logged with id 76i6e5ofd.`

**Comment by ejunprung** [comment]
@JavaFXpert I was able to fix this issue on my Macbook. You may want to delete your current Docker SKIL image and reinstall using the instructions at https://hub.docker.com/r/skymindops/skil-ce/. It also explains how to persist data.

**Comment by slinlee** [comment]
This should be fixed in more recent versions of SKIL-CE. I also improved the error messages with https://github.com/SkymindIO/lagom-skil-api/pull/1269
