### ISSUE TITLE
Zeppelin Notebook URLs broken

### ISSUE THREAD

**Issue by ejunprung** [SkymindIO/SKIL-CE#14]
The text URLs are broken. For example, ND4J links to https://%20//nd4j.org/doc/.

![screen shot 2018-01-10 at 12 50 47 pm](https://user-images.githubusercontent.com/5703667/34794910-16c88dae-f605-11e7-9f46-1a6d46a74f93.png)

**Comment by wmeddie** [comment]
Fixing this unfortunately causes other problems.  I'll keep an eye out for other solutions.
