### ISSUE TITLE
It's not clear when forms are submitted and they allow multiple submissions

### ISSUE THREAD

**Issue by nkwoh01** [SkymindIO/SKIL-CE#15]
I’ve come across a small lag after clicking Create Workspace or New Experiment. I’m not sure whether my input is submitted and I click a bunch of times and it generates a gazillion of the same workspace or experiment. This could be addressed with the UI acknowledging that I clicked the button but that it needs 15 seconds? ie. an animated ellipsis

It occurs inconsistently; most of the time it’s fine.

![screen shot 2018-01-10 at 4 38 05 pm](https://user-images.githubusercontent.com/35175038/34803061-fdea1250-f625-11e7-8228-2a1930e2d5cc.png)
![screen shot 2018-01-10 at 4 37 31 pm](https://user-images.githubusercontent.com/35175038/34803059-f959fa0c-f625-11e7-8612-93d841eab5bc.png)

**Comment by slinlee** [comment]
@nkwoh01 Those are good suggestions. I'll add some changes that make it obvious the form was submitted and is processing, and also prevents you from submitting it again until it's done. (with either a success, or error)

**Comment by slinlee** [comment]
Along with the Ui changes to show when the forms are being submitted (above), I also made some improvements on the error messages shown, https://github.com/SkymindIO/lagom-skil-api/pull/1269
