### ISSUE TITLE
When I restart Docker SKIL, everything is cleared

### ISSUE THREAD

**Issue by nkwoh01** [SkymindIO/SKIL-CE#16]
Include in install / docs -

For everything to be persistent you typically need docker mounted volumes:
https://docs.docker.com/engine/admin/volumes/

Docker containers are by definition not persistent.

**Comment by slinlee** [comment]
@nkwoh01 Here is some new documentation we added about setting up docker to persist your data:
https://docs.skymind.ai/v1.0.1/docs/docker-image#section-persistent-data
