### ISSUE TITLE
Experiment SyntaxError: Unexpected Token < in JSON at position 2

### ISSUE THREAD

**Issue by ejunprung** [SkymindIO/SKIL-CE#17]
I think this error is unique to SKIL Docker when persisting data.

At first start (zero state), it works with no error. However, re-loading SKIL (with previously saved experiments), I get the error in the screenshot below. I think it's because an experiment is trying to call an unauthenticated notebook. Not sure, though. 

![screen shot 2018-01-13 at 12 46 37 am](https://user-images.githubusercontent.com/5703667/34904465-8f6e285c-f7fb-11e7-9d94-0c77f8d771e3.png)

**Comment by tomthetrainer** [comment]
I get a similar error, 

at position 1

<img width="342" alt="screen shot 2018-03-05 at 11 40 48 pm" src="https://user-images.githubusercontent.com/864671/37014448-c4cecff0-20ce-11e8-93fa-a11131f1ac0e.png">

Not seeing any resolution to this I will re-install. 

Oh my platform would be SKIL install via rpm on Centos VM

**Comment by slinlee** [comment]
I improved the error message in #1269 and I'm going to close this. If you still see the original issue, can you re-open this? Thanks @ejunprung
