### ISSUE TITLE
Difficulty understanding how to running skil server after installed using Docker (Mac)

### ISSUE THREAD

**Issue by chiaweil** [SkymindIO/SKIL-CE#18]
After running the command "docker run --rm -it -p 9008:9008 -p 8080:8080 skymindops/skil-ce bash /start-skil.sh", uncertain about what to expect.

More elaborative explanations or screenshot of the terminal and browser running "http://localhost:9008" will be helpful.

**Comment by wmeddie** [comment]
I added some screenshots to the instructions.
