### ISSUE TITLE
Why disable SELinux?

### ISSUE THREAD

**Issue by cliffbdf** [SkymindIO/SKIL-CE#2]
Nice system. One concern: the docs say, "First, you must disable SELinux."

Really? Why? This is an application - not a system tool. Disabling SELinux should not be necessary. What is the specific reason why SELinux must be disabled? There is probably a way to avoid that. Some detailed info would enable people to find another way that doesn't require disabling SELinux.

Thanks.

**Comment by tomthetrainer** [comment]
Thanks for the issue report, I will check with the team and see if we have the details on why we made that decision.

**Comment by jpatanooga** [comment]
For this initial release we had a few things that it didnt like, and decided to go on with disabling it.

For the 1.0.1 point release (first week of Dec) we'll have this resolved.

**Comment by cliffbdf** [comment]
That helps a-lot. If disabling SELinux is a temporary requirement, it is easier to justify disabling it - because it is temporary (obviously ;-) )

Thanks.
