### ISSUE TITLE
Dead link in the documentation

### ISSUE THREAD

**Issue by RobAltena** [SkymindIO/SKIL-CE#22]
The link to java dependencies: https://docs.skymind.ai/docs/dependencies gives a 404-not found.

On the https://docs.skymind.ai/docs/maven page.

Another one. On the zeppelin title page 404s: 
Get started with [Zeppelin documentation](http://zeppelin.apache.org/docs/0.7.3_skil-1.0.1/index.html)

**Comment by slinlee** [comment]
@RobAltena thanks. I think @crockpotveggies or @ejunprung should be able to fix these asap.

**Comment by ejunprung** [comment]
I've removed the link to https://docs.skymind.ai/docs/dependencies. I'm not sure where that is supposed to go.

As for the dead Zeppelin documentation link, which page do you see that on? I can't seem to find it. @RobAltena

**Comment by RobAltena** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/13833070/35710331-2f513522-07fa-11e8-94c8-493e2a9418e8.png)

**Comment by ejunprung** [comment]
Ah, that's within the SKIL dashboard. @slinlee and @wmeddie would need to fix that.

**Comment by slinlee** [comment]
The link to the Zeppelin docs will be fixed with the next release.

**Comment by smichea** [comment]
Still have the issue about zeppelin doc link pointing to http://zeppelin.apache.org/docs/0.7.3_skil-1.1.0/index.html  in the lastest docker image skymind/skil
