### ISSUE TITLE
Error deleting workspace.

### ISSUE THREAD

**Issue by RobAltena** [SkymindIO/SKIL-CE#23]
Both form the workspaces page and the workspace page.

"Syntax error, unexpected token E in JSON at position 0."

**Comment by slinlee** [comment]
@RobAltena Sorry about that error message. It's not useful at all. For now, to delete a workspace you need to delete any experiments in that workspace.

We have an issue open for that. https://github.com/SkymindIO/lagom-skil-api/issues/893

**Comment by RobAltena** [comment]
Works for me. Thank you!
