### ISSUE TITLE
Spark crashing with a "NoClassDefFoundError" under IntelliJ/Scala

### ISSUE THREAD

**Issue by nkwoh01** [SkymindIO/SKIL-CE#24]
Spark running ok under IntelliJ / Java. But crashing with a "NoClassDefFoundError" on that same machine under IntelliJ / Scala.

Found on basecamp posted by Robert Altena
https://3.basecamp.com/3684163/buckets/6475638/chats/895341926

**Comment by ShamsUlAzeem** [comment]
Don't think this is relevant right now
