### ISSUE TITLE
SKIL on port serverx:9008 wraps local_server:8080 as notebook 

### ISSUE THREAD

**Issue by tomthetrainer** [SkymindIO/SKIL-CE#25]
Not sure if this is an issue that needs patched or not but we should be aware of it. 

I have a host machine and I am running tomcat on port 8080
<img width="713" alt="screen shot 2018-03-03 at 12 29 47 am" src="https://user-images.githubusercontent.com/864671/36930984-d3c25596-1e7a-11e8-8c5f-fb13e63e6731.png">

When I run SKIL in a guest VM it runs a webserver on port 9008, 

So I forward 127.0.0.1:9008 to guestVM:9008

When I create and go to use a notebook from the Host machine, I see the contents of http_get_localhost:8080, not http_get_guest. 

See here, 
<img width="612" alt="screen shot 2018-03-03 at 12 33 03 am" src="https://user-images.githubusercontent.com/864671/36930987-dbe0def0-1e7a-11e8-8454-3b7e17f7545d.png">

So not perhaps an issue, but maybe can be avoided by hardcoding IP address once or something.

**Comment by wmeddie** [comment]
Need to close this as won't fix.  Being able to access the notebook directly is useful for integration purposes.
