### ISSUE TITLE
Deployment UI Feedback

### ISSUE THREAD

**Issue by ejunprung** [SkymindIO/SKIL-CE#26]
![screen shot 2018-03-04 at 10 44 15 pm](https://user-images.githubusercontent.com/5703667/36960865-bb92d16a-1ffd-11e8-88df-436d2883e75b.png)

Just a couple tweaks that I thought of. 

1. Perhaps make the Endpoint URL "copy-able"? I had trouble copy/pasting it out. For example, some UIs have a "copy" button when you mouse over it. Or you could just make it easier to highlight by rendering it as an actual link vs button (I do see that you planned to pop a modal with further instruction in the future, right?).
2. http://host:9008 --> Would be nice if SKIL dynamically inserted the actual host so when I copy and paste, I won't have to type it in.

**Comment by slinlee** [comment]
@ejunprung good feedback. FYI a fix for both of these was merged on Feb 22 so it should be fixed in a public release soon. https://github.com/SkymindIO/lagom-skil-api/pull/1115
