### ISSUE TITLE
Process viewer

### ISSUE THREAD

**Issue by tomthetrainer** [SkymindIO/SKIL-CE#27]
Right now I am training a model in SKIL, 

It is taking some resources and has obviously spawned a java process. 

It would be nice to be able to manage that process somehow. Or at least view it. 

For example right now I see SKIL using the following processes

9030 skil      20   0 14.439g 2.264g   8040 S  74.1 24.5  38:17.11 java
 4676 skil      20   0 4608756 247108   6032 S  28.2  2.5   0:31.92 java
 4695 skil      20   0 11.705g 1.250g   5700 S   2.0 13.5   1:12.57 java
 4626 skil      20   0 6336260 687472   6556 S   1.0  7.1   1:11.76 java
 4964 skil      20   0 6994244 1.569g   4200 S   0.7 16.9   0:45.70 java
  320 root       0 -20       0      0      0 S   0.3  0.0   0:00.21 kworker/

Something like a top, or a ps -afx for SKIL processes

**Comment by ShamsUlAzeem** [comment]
Training in SKIL is mostly done with Zeppelin. Otherwise, we are using jobs to do that and we already have tools to view those processes and their status.
