### ISSUE TITLE
GPG key retrieval failed.

### ISSUE THREAD

**Issue by nikhil791** [SkymindIO/SKIL-CE#29]
Hi,

whenever I hit this command on my centos 7----->  sudo yum install skil-server skil-server-miniconda skil-server-spark

I get this following error.
GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle"

can anyone help me how to resolve this issue..?

**Comment by tomthetrainer** [comment]
That is a strange error, IMO, but perhaps it would make sense to 
@emsixteeen

**Comment by ShamsUlAzeem** [comment]
Newer install instructions are here: https://skymind.ai/download
