### ISSUE TITLE
JSON parse error when creating notebook

### ISSUE THREAD

**Issue by stealthman13** [SkymindIO/SKIL-CE#3]
I installed Skil-CE on a CentOS7 machine and successfully created a Workspace, but when creating a new experiment, I get a red error box that says "Create notebook SyntaxError: Unexpected token E in JSON at position 0"

**Comment by wmeddie** [comment]
I wonder if zeppelin is running correctly.  Do you by chance have some other server listening on port 8080?

**Comment by stealthman13** [comment]
Ah yes, apparently someone else turned on a server on 8080.  I turned it off and everything is working now.  Everything works and looks great. Well done.
