### ISSUE TITLE
Not obvious that you should enter to register input and output placeholder

### ISSUE THREAD

**Issue by ejunprung** [SkymindIO/SKIL-CE#31]
![inputoutput](https://user-images.githubusercontent.com/5703667/37631029-f80ebd86-2ba4-11e8-81b1-0d38d62869fb.png)

I didn't realize you had to manually click "enter" to register the placeholders. The SKIL dashboard allowed me to import a model with invalid placeholders which caused the deployment to fail.

**Comment by slinlee** [comment]
@ejunprung - Good news, @wmeddie just fixed this with better instructions on the label and making the placeholders save automatically when you move on from the field. https://github.com/SkymindIO/lagom-skil-api/pull/1210

**Comment by ejunprung** [comment]
Awesome
