### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by rezacsedu** [SkymindIO/SKIL-CE#32]
Hi there,

I would like to install SKIL on Ubuntu. Is there any plan for the Ubuntu users?

**Comment by tomthetrainer** [comment]
@nkwoh01 
Do you have a roadmap for ubuntu support?

**Comment by tomthetrainer** [comment]
You could use the docker image with Skil CE pre-installed. 
https://docs.skymind.ai/docs/docker-image

**Comment by ShamsUlAzeem** [comment]
Duplicate of #8
