### ISSUE TITLE
Error uploading vgg16_weights.h5 into Docker SKIL-CE

### ISSUE THREAD

**Issue by melchisadeck** [SkymindIO/SKIL-CE#33]
Hi,

I have SKIL-CE running in a Docker Version 18.03.0-ce-mac60 (23751) with 8GB or RAM on Mac OS High Sierra 10.13.3 on Macbook Pro 2016 with 16GB of RAM.

I browse to localhost:9008 and login to SKIL using admin/admin.

From my reading of the SKIL-CE Quickstart, Keras Models in HDF5 can be imported so I create Deployment "vgg16" and attempt to Import Model "vgg16_import" from file vgg16_weights.h5.

I obtained the .h5 file at "VGG-16 pre-trained model for Keras" at the following link:
https://gist.github.com/baraldilorenzo/07d7802847aaad0a35d3

During upload, I receive the following error:
"File upload There was an error uploading the file. Please try again".

Any help much appreciated.

Thanks,
Mel

**Comment by wmeddie** [comment]
We are tracking the problem with the model import here: https://github.com/deeplearning4j/deeplearning4j/issues/4916 

I'll update this issue when a fix is released.

**Comment by maxpumperla** [comment]
@melchisadeck was this model built with theano or tf? Fix is inbound here: https://github.com/deeplearning4j/deeplearning4j/pull/4920

**Comment by eraly** [comment]
@maxpumperla The model was build with the theano backend.

@melchisadeck FYI, you cannot use the vgg16_weights.h5 file in that gist. Those only contain weights. So to upload the model into skil it would have to be an h5 that is written out with both the weights and the model config like I describe in the issue Eduardo linked to.

**Comment by eraly** [comment]
Copy pasting from the dl4j issue some user notes on SKIL so it doesn't get forgotten.

--------------------------------------------------------------------------------------

Thanks all for your engagement on this.

I downloaded vgg16_compiled.h5 provided by @eraly at the link above and attempted to import - after about 25 seconds I received the "upload failed try again" message, exactly as before.

Then, just to see what happens, I attempted to import another random file from my Downloads folder - an Acrobat PDF file of 5.7Mb.

The "upload failed" message persisted and above it I received an "Imported Model Successfully Imported Model" message and the model appears to be imported, startable, stopable, etc. - screen shot attached.

I've tried this with a .pdf file of 5.7MB, a .png file of 2.3MB and an .m3u file of 94 bytes, stopping and starting docker between each model import - random .pdf/.png/.m3u import attempt and each time the vgg16_compiled.h5 import appears to complete successfully.

I haven't attempted to send data to the imported/running model but I thought this observation may help.

Regards,
Mel

![image](https://user-images.githubusercontent.com/8340500/38697025-a44e2afc-3e45-11e8-9909-fc58ca51dfc1.png)

**Comment by wmeddie** [comment]
I discovered the source of the File Upload issue.

The Web framework SKIL uses creates a random /tmp/playtempXXXX folder on start up to hold any uploaded files.  But if a day or two goes by with no uploads the CentOS tempfile service will delete the folder.  The Next version of the docker will include a configuration to exclude those folders from deletion.  In the mean time, restarting the daemon with `systemctl stop skil && sleep 10s '' systemctl start skil` should re-enable file uploads.

To prevent the upload directory deletion.  You can add the following line to `/usr/lib/tmpfiles.d/tmp.conf`

```
# Ignore playtemp for SKIL
X /tmp/playtemp*

```
