### ISSUE TITLE
Unable to delete a workspace

### ISSUE THREAD

**Issue by ejunprung** [SkymindIO/SKIL-CE#35]
I'm not sure what the issue is. I can't delete my old workspaces.

![screen shot 2018-04-22 at 10 23 22 pm](https://user-images.githubusercontent.com/5703667/39108197-d4040d82-467b-11e8-8e26-5c1a7164e6b9.png)

**Comment by abhishekpathak** [comment]
Does the workspace have experiments inside? SKIL currently only supports deleting empty workspaces: https://github.com/SkymindIO/lagom-skil-api/issues/893

**Comment by ejunprung** [comment]
@abhishekpathak That was the issue. Thanks!
