### ISSUE TITLE
Cant connect to mysql...

### ISSUE THREAD

**Issue by P00LDEAD** [SkymindIO/SKIL-CE#39]
I'm running fedora 26 and I loaded skil and mysql by following the steps at https://docs.skymind.ai/docs/multiple-servers... However I cant connect to the mysql database... I am able to remote into mysql using the skil login... I double checked the ip address and mysql is listening on port 3306 for all incoming requests... the db name is also correct...

Here is the error I'm receiving:

19:31:55.931 [main] INFO  io.skymind.db.DataBaseManager - previous location: classpath:db/migration
19:31:55.931 [main] INFO  io.skymind.db.DataBaseManager - updated location: classpath:db/migration/mysql
19:31:55.931 [main] INFO  io.skymind.db.DataBaseManager - updated locations with "mysql"
19:31:55.994 [main] ERROR io.skymind.db.DataBaseManager -
Unable to obtain connection from database (jdbc:mysql://192.168.1.100:3306/skil_migrations) for user 'skil': Could not create connection to database server.
------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Could not create connection to database server.

**Comment by wmeddie** [comment]
Any chance a firewall might be blocking access to port 3306 from the server running SKIL?

**Comment by P00LDEAD** [comment]
Unfortunately not... I disabled my firewall...

If I change my skil-env.sh and update the jdbc url from an IP address to the computer name, I get the following error:

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server. (caused by node0) Retrying in 1 sec...
20:05:38.918 [main] ERROR io.skymind.db.DataBaseManager -
Unable to obtain connection from database (jdbc:mysql://node0:3306/skil_migrations) for user 'skil': Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08S01
Error Code : 0
Message    : Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

**Comment by P00LDEAD** [comment]
Here is my skil-env.sh file:

SKIL_HOME=/opt/skil
SKIL_CLASS_PATH=/opt/skil/lib/*:/opt/skil/native/*:/etc/skil/*
SKIL_LOG_DIR=/var/log/skil
SKIL_PID_FILE=/run/skil/skil.pid

SKIL_BACKEND=cpu
SKIL_LICENSE_PATH=/etc/skil/license.txt
SKIL_PUBLIC_KEY_PATH=/etc/skil/publickey.txt
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
JDK_HOME=$JAVA_HOME

SKIL_SERVER_PROD_MODE=true

ZOOKEEPER_HOST=192.168.1.100
ZOOKEEPER_PORT=2181
ZOOKEEPER_EMBEDDED=false

SKIL_USE_EMBEDDED_DB=false
SKIL_DB_NAME=skil_migrations
SKIL_DB_DRIVER=com.mysql.jdbc.Driver
SKIL_DB_URL=jdbc:mysql://node0:3306/skil_migrations
SKIL_DB_USER=skil
SKIL_DB_PASSWORD=myPassword
MODEL_HISTORY_SERVER_LAUNCH_DEFAULT=false
ZEPPELIN_LAUNCH_DEFAULT=false

SPARK_HOME=/opt/spark

**Comment by wmeddie** [comment]
Is your SELinux set to enforcing by any chance?

**Comment by P00LDEAD** [comment]
Nope... Disabled it...

**Comment by wmeddie** [comment]
What is the command you used to create the mysql user? Is the host running SKIL the same as the mysql host?  One possible problem is if you used the following SQL to create the user:

GRANT ALL PRIVILEGES ON *.* TO 'skil'@'localhost' IDENTIFIED BY 'skil';

if the server isn't localhost it won't be able to log in.  In that case use either 'skil'@'{your SKIL IP}' or 'skil'@'%' instead.

**Comment by P00LDEAD** [comment]
They are running on the same server... But here are the commands I used:

CREATE USER 'skil'@'%' IDENTIFIED BY 'myPassword';

GRANT ALL PRIVILEGES ON *.* TO 'skil'@'%';

I granted all privileges on everything to skil just to be safe... I figured once I get it operational, I will update the privileges accordingly...

**Comment by P00LDEAD** [comment]
I restarted my box and when I tried starting skil I noticed the error looked differently... It says this:

Unable to obtain connection from database (jdbc:mysql://192.168.1.100:3306/skil_migrations) for user 'skilSKIL_DB_PASSWORD=myPassword!': Could not create connection to database server.

notice: 'skilSKIL_DB_PASSWORD=myPassword!'

**Comment by P00LDEAD** [comment]
I ended up switching my jdbc driver from Connector/J 8.0 to Connector/J 5.1.46, then made a new symbolic link replacing the old one... After that, I was able to establish a connection to mysql... 

Not sure why the Connector/J 8.0 doesnt work...

**Comment by wmeddie** [comment]
Oh good find.  I was running out of ideas.  I'll make sure we add some documentation on Connector/J 8.0.

**Comment by P00LDEAD** [comment]
OK... I have another issue trying to login to skil via web browser... I posted a new thread... I would greatly appreciate it if you could help with that one as well...
