### ISSUE TITLE
Setting up skymind's skil service

### ISSUE THREAD

**Issue by jpmantuano** [SkymindIO/SKIL-CE#4]
I'm trying to setup the skymind's skil service on my local, trying to follow a similar architecture to what is on this page (https://skymind.ai/platform). I would love to have some more readings about setting this up.

I already have tensorflow setup and a psuedo hadoop cluster together with spark, and working my way into the integration witht he workspace and model server.

**Comment by abhishekpathak** [comment]
We are working on improving the documentation. Meanwhile, if you face any problems setting this up, please create an issue and we'll help you out.

**Comment by wmeddie** [comment]
Please see the new documentation site at https://skymind.readme.io/v1.0.1/docs and lets us know again if there's anything missing.
