### ISSUE TITLE
Unable to create experiment in SKIL 1.1.1

### ISSUE THREAD

**Issue by chiaweil** [SkymindIO/SKIL-CE#42]
Installed SKIL 1.1.1 in mac using docker. Unable to create experiment.

SKIL Version 1.1.1
DL4J Version 1.0.0-beta
ND4J Version 1.0.0-beta
Supported Spark Version 1.6.3
Supported Scala Version 2.10

￼
<img width="1019" alt="exp1" src="https://user-images.githubusercontent.com/34699343/42752709-5881c04e-8921-11e8-8b51-6e841eb19a56.png">

**Comment by wmeddie** [comment]
This is due to the zeppelin server re-downloading the interpreters.  I'll fix it soon. In the meantime just wait for the log: "About to join jetty web server" before using SKIL.

**Comment by xwyfct** [comment]
Installed SKIL 1.1.1 in linux using package. Unable to create experiment.

![default](https://user-images.githubusercontent.com/34887506/44971707-3470fb00-af89-11e8-90d1-6949768461d0.png)

**Comment by ShamsUlAzeem** [comment]
This is fixed in our latest [docker image](https://hub.docker.com/r/skymindops/skil-ce/). Just wait for the message `SKIL READY` before using the application.
