### ISSUE TITLE
YOLO demo appears broken in the latest version of SKIL

### ISSUE THREAD

**Issue by ejunprung** [SkymindIO/SKIL-CE#44]
This was reported to me by a user. We are running the YOLO demo located at https://github.com/SkymindIO/SKIL_Examples/tree/master/skil_yolo2_app. 

SKIL Version 1.1.1
DL4J Version 1.0.0-beta
ND4J Version 1.0.0-beta
Supported Spark Version 1.6.3
Supported Scala Version 2.10

It is resulting in the following exception: https://gist.github.com/ejunprung/17ce1054a72e5ad80fcd3c335e688b7b.

I think the example code may be out-of-date, but I am not sure. We are following this tutorial: https://blog.skymind.ai/building-a-production-grade-object-detection-system-with-skil-and-yolo/.

**Comment by ShamsUlAzeem** [comment]
@ejunprung ask them about what they named their deployment and the model (both of them should be yolo) while deploying it. It says that no route found here: 
`Return: {"error":"Illegal id yolo/model/yolo no route found"}`

**Comment by ejunprung** [comment]
Hey @ShamsUlAzeem,

I can confirm that both the deployment and model are named "yolo". So if I query:

**No backslash at the end of the URL** 
http://localhost:9008/endpoints/yolo/model/yolo/default --> Return: {"error":"Illegal id yolo/model/yolo no route found"}

**Backslash at the end of URL**
http://localhost:9008/endpoints/yolo/model/yolo/default/ --> Return: {"error":"Request failure"}
https://gist.github.com/ejunprung/60159d47e5e0fa1186de819e5cf52b4f

Do you happen to know if that makes a difference?

**Comment by ShamsUlAzeem** [comment]
Hmm interesting. I'll try the tutorial on the newer SKIL and let you know

**Comment by wmeddie** [comment]
http://localhost:9008/endpoints/yolo/model/yolo/default --> Return: {"error":"Illegal id yolo/model/yolo no route found"}

That's expected.  We don't have a get route defined for model servers.

http://localhost:9008/endpoints/yolo/model/yolo/default/ --> Return: {"error":"Request failure"}
https://gist.github.com/ejunprung/60159d47e5e0fa1186de819e5cf52b4f

I think this is fixed in 1.1.3.  Which will be released as soon as I figure out the reason docker always re-downloads the interpreters.

**Comment by ejunprung** [comment]
@wmeddie Ah, I see. I'll try again in 1.1.3. Thanks!

**http://localhost:9008/endpoints/yolo/model/yolo/default --> Return: {"error":"Illegal id 
yolo/model/yolo no route found"}**

This might be an issue because it means the SKIL GUI is displaying the endpoint incorrectly. For people who copy and paste (like me), I wouldn't notice that it's missing a backslash at the end. @slinlee 

![screen_shot_2018-07-23_at_3_46_01_pm](https://user-images.githubusercontent.com/5703667/43106970-c86d0242-8e8f-11e8-8d26-6c7b5e6caad7.png)

**Comment by wmeddie** [comment]
Wait I took off the backslash because the extra backslash breaks the skil-clients.

**Comment by ShamsUlAzeem** [comment]
@ejunprung was this issue solved for you?

**Comment by ejunprung** [comment]
I think it's fixed. I have been running YOLO locally on the latest SKIL and I haven't had issues.

**Comment by ShamsUlAzeem** [comment]
Awesome!
