### ISSUE TITLE
Failed to run SKIL after persist data.

### ISSUE THREAD

**Issue by chiaweil** [SkymindIO/SKIL-CE#46]
Referring to this [https://hub.docker.com/r/skymindops/skil-ce/](url) to persist the content. 

SKIL Version 1.1.1
DL4J Version 1.0.0-beta
ND4J Version 1.0.0-beta
Supported Spark Version 1.6.3
Supported Scala Version 2.10

Ran the following command 
_docker run --rm -it --name skil -v skil-data:/var/skil --env SKIL_EMBEDDED_DB_PATH=/var/skil/skildb --env ZOOKEEPER_EMBEDDED=false --env ZOOKEEPER_HOST=zookeeper --env ZOOKEEPER_PORT=2181 --link zookeeper:zookeeper -p 9008:9008 -p 
8080:8080 skymindops/skil-ce:1.1.1-1 bash /start-skil.sh_

**ZeppelinInterpreterMain, ModelHistoryServer, ZeppelinMain** processes does not run with the above command.

**Comment by wmeddie** [comment]
Ah it looks like the stop-skil script isn't being run properly. (before you could press enter to run stop-skil but as it is now you can only kill the log tail.  I'll add this to the things that need fixing in the docker and post here when I've fixed the start-skil script.

**Comment by ShamsUlAzeem** [comment]
@wmeddie is this fixed? Does it run the stop script now when we kill the running container?

**Comment by ShamsUlAzeem** [comment]
There are still problems with persisting images

**Comment by ShamsUlAzeem** [comment]
The new instructions for persisting data are here: https://hub.docker.com/r/skymind/skil
