### ISSUE TITLE
Apache Zeppelin

### ISSUE THREAD

**Issue by LifeOfBinaries** [SkymindIO/SKIL-CE#50]
when i start docker skymind , i m not unable to start getting following error:

docker pull apache/zeppelin command not working

grep: /var/log/skil/zeppelin-*.log: No such file or directory 
Waiting for interpreter install...

**Comment by wmeddie** [comment]
We’ve noticed this issue as well. And are working on a fix very soon.

For informational purposes. What is the OS of the machine running Docker.
And how much memory does it have?

-- 
eduardo@skymind.io

**Comment by LifeOfBinaries** [comment]
OS:Kali Linux with 8 GB
*Regards,*
*Rajiv Ranjan*
*Mob: +919311245650*

**Comment by jhp0120** [comment]
same thing happens to me

**Comment by wmeddie** [comment]
Hi everyone. I’ve uploaded a release candidate of 1.1.4 to my Docker hub. We have tested it on Mac and Windows and the issue looks to be fixed. Can you try running with the following command and let me know if you run into issues?

docker run --rm -it -p 9008:9008 -p 8080:8080 wmeddie/skil-ce:1.1.4-1 bash /start-skil.sh

**Comment by nsriram13** [comment]
Was this issue fixed? I am still seeing this issue with the image tagged `latest` in DockerHub. I can log into the landing page via the browser and create a workspace. But I am unable to create a new notebook for an experiment. Thanks for the troubleshooting help.

**Comment by ShamsUlAzeem** [comment]
@nsriram13 can you try the docker image from Skymind's dockerhub? There have been a couple of updates with it. 

Run these commands: 

```
docker pull skymindops/skil-ce
docker run --rm -it -p 9008:9008 -p 8080:8080 skymindops/skil-ce bash /start-skil.sh
```

For creating notebooks inside workspaces, can you confirm if you can access the zeppelin server at port `8080`?

**Comment by ShamsUlAzeem** [comment]
The newer docker images are here https://hub.docker.com/r/skymind/skil

So this issue is outdated now
