### ISSUE TITLE
skil.service failed

### ISSUE THREAD

**Issue by qntbkk** [SkymindIO/SKIL-CE#51]
![image](https://user-images.githubusercontent.com/30016946/49746351-94d3af00-fcd3-11e8-9c3a-d5d73d3c7a7a.png)

**Comment by wmeddie** [comment]
Can you share the files inside /var/log/skil?

**Comment by wmeddie** [comment]
Ah, good to know.  Do you mean you installed the skil-server-miniconda but it failed and you ran install-python.sh manually?  Or did you install the skil-server-miniconda package again?

I wonder if this is related to the SSL issues we've started seeing yesterday.

**Comment by qntbkk** [comment]
you are right, just install-python.sh manually. but haven’t finish yet, still a lot of stuff need to config, but at least when i run skil again there is no error message.

**Comment by ShamsUlAzeem** [comment]
@wmeddie I think we solved this before but it's still not working for some reason with the miniconda RPM.

**Comment by wmeddie** [comment]
The miniconda RPM looks like it doesn’t work anymore. It hasn’t changed. So I think it’s just some change to versions. So I’ve changed the docs to tell people to use the static-conda RPM.

**Comment by ShamsUlAzeem** [comment]
Right. I'll start working on the fix for this.

**Comment by ShamsUlAzeem** [comment]
We're using the static conda distro now or we install it manually.
