### ISSUE TITLE
SKIL activation pages need to go to top

### ISSUE THREAD

**Issue by crockpotveggies** [SkymindIO/SKIL-CE#55]
After submitting the license form, the page needs to scroll back to the top.

<img width="1439" alt="Screen Shot 2019-04-17 at 12 46 58 AM" src="https://user-images.githubusercontent.com/1445295/56270202-71b67300-60aa-11e9-9ae3-29925006a76c.png">

**Comment by ShamsUlAzeem** [comment]
@ejunprung cam you sort this out?

**Comment by ejunprung** [comment]
@ShamsUlAzeem Will do. I'll add it to my list of things to polish.

**Comment by ejunprung** [comment]
Hey, let's fix this one later. I'm having trouble finding a quick solution because the activate form loads in an iframe. Don't think it's a huge issue for now.

**Comment by slinlee** [comment]
Issue moved to [SkymindIO/skil-server #2153](https://github.com/SkymindIO/skil-server/issues/2153) via [**ZenHub**](https://www.zenhub.com/)

**Comment by slinlee** [comment]
Issue moved to [SkymindIO/skil-server #2154](https://github.com/SkymindIO/skil-server/issues/2154) via [**ZenHub**](https://www.zenhub.com/)
