### ISSUE TITLE
Notebook file upload size cannot exceed 0MB

### ISSUE THREAD

**Issue by crockpotveggies** [SkymindIO/SKIL-CE#56]
Looks like notebook upload is broken in 1.2.1 since it states a notebook cannot exceed 0MB. Is this a bug or a license limitation? If licensing related it should explicitly state the reason.

<img width="1036" alt="Screen Shot 2019-04-18 at 10 59 16 AM" src="https://user-images.githubusercontent.com/1445295/56381297-51310a80-61c9-11e9-84d3-c74e674a942f.png">

**Comment by ShamsUlAzeem** [comment]
Pretty sure this is not a license limitation. It's probably something due to zeppelin configurations. Had seen this error before but the configuration looked fine to me. I'll investigate it with the zeppelin configuration

**Comment by ShamsUlAzeem** [comment]
This is resolved now

**Comment by smichea** [comment]
@ShamsUlAzeem i encounter this also in the latest docker image

**Comment by wmeddie** [comment]
Next release fixes this.  You can preview it here: https://cloud.docker.com/u/skymind/repository/docker/skymind/skil-snapshots by running the following command:

```
    docker run -it -p 9008:9008 -p 8080:8080 skymind/skil-snapshots:1.2.2-zepp-exp
```
