### ISSUE TITLE
How to enable zeppelin remote debugging inside SKIL?

### ISSUE THREAD

**Issue by tgreiser** [SkymindIO/SKIL-CE#6]
Trying to follow the zeppelin instructions for remote debugging ([Advanced Diagnose Approach](https://community.hortonworks.com/articles/70658/how-to-diagnose-zeppelin.html)). I modify /var/skil/zepp/conf/zeppelin-env.sh, but when I run `systemctl restart skil` my changes to zeppelin-env.sh are overwritten.

Name : skil-server
Arch : x86_64
Version : 1.0.0
3.10.0-693.el7.x86_64
CentOS 7

**Comment by wmeddie** [comment]
The default Zeppelin server is managed by SKIL so it'll overwrite any changes to zeppelin.  We do have a couple of ways to add debugging but they aren't applicable to the default Zeppelin server.  We will include a flag to enable this properly in the next release.
