### ISSUE TITLE
SyntaxError: JSON.parse after installing SKIL-CE

### ISSUE THREAD

**Issue by Shedyk** [SkymindIO/SKIL-CE#7]
Fresh install of SKIL CE I get an error .. SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data https://screenshots.firefox.com/zatcfAopAauoOQPa/104.200.25.41
server:CentOS 7
java: openjdk version "1.8.0_151"

**Comment by tomthetrainer** [comment]
When does this error occur?

During the install, or when loading a notebook? If the error occurs when loading a notebook please provide more details.

**Comment by Shedyk** [comment]
It pops up just after I log in and again when I try to create a workspace another pops up(same error message). Creating workspace fails.

**Comment by Shedyk** [comment]
Found this in the skil-error.log 

> SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/skil/lib/slf4j-log4j12-1.7.19.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/skil/lib/logback-classic-1.1.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/skil/lib/zeppelin-spark_2.11-0.7.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Nov 16, 2017 6:28:32 PM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.InterpreterRestApi.listInterpreter(java.lang.String), should not consume any entity.
WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.CredentialRestApi.getCredentials(java.lang.String) throws java.io.IOException,java.lang.IllegalArgumentException, should not consume any entity.
WARNING: The (sub)resource method createNote in org.apache.zeppelin.rest.NotebookRestApi contains empty path annotation.
WARNING: The (sub)resource method getNoteList in org.apache.zeppelin.rest.NotebookRestApi contains empty path annotation.

I have attached the skil.log file, notably error below occurs when I click create workspace
[skil.log](https://github.com/SkymindIO/SKIL-CE/files/1479803/skil.log)

> java.lang.RuntimeException: java.net.MalformedURLException: For input string: "3c01:0:0:f03c:91ff:feeb:24f3%eth0:9100"
	at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:183)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at io.skymind.skil.predict.loadbalance.DynamicPathClientProcessor.process(DynamicPathClientProcessor.java:155)

**Comment by wmeddie** [comment]
@Shedyk Thanks for posting those logs.  It looks like your system is set to use IPv6 addresses.  I'm afraid we can't support this configuration at the moment since it won't mesh well with Hadoop.

https://wiki.apache.org/hadoop/HadoopIPv6

If you can give us some details about your network configuration I'll see if it's something we can address in the documentation or post-install.

**Comment by tomlock** [comment]
Disabling ipv6 will do the job.

```
# vi /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="ipv6.disable=1 crashkernel=auto rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
```
